package me.kk47.modeltrains.client.model;

import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelLoggingCarEmpty extends MTmModelBase{
  //fields
    ModelRenderer Base;
    ModelRenderer Wheel1;
    ModelRenderer Wheel2;
    ModelRenderer Wheel3;
    ModelRenderer Wheel4;
    ModelRenderer Wheel5;
    ModelRenderer Wheel6;
    ModelRenderer Wheel7;
    ModelRenderer Wheel8;
    ModelRenderer Axel1;
    ModelRenderer Axel2;
    ModelRenderer Axel3;
    ModelRenderer Axel4;
    ModelRenderer Truck1;
    ModelRenderer Truck2;
    ModelRenderer Truck3;
    ModelRenderer Truck4;
    ModelRenderer HodlingBeam0;
    ModelRenderer HoldingBeam1;
    ModelRenderer HoldingBeam2;
    ModelRenderer HoldingBeam3;
    ModelRenderer HoldingBeam4;
    ModelRenderer HodlingBeam5;
    ModelRenderer HoldingBeam6;
    ModelRenderer HoldingBeam7;
    ModelRenderer HoldingBeam8;
    ModelRenderer HoldingBeam9;
    ModelRenderer Coupler1;
    ModelRenderer Coupler2;
  
  public ModelLoggingCarEmpty()
  {
    textureWidth = 128;
    textureHeight = 32;
    
      Base = new ModelRenderer(this, 32, 0);
      Base.addBox(0F, 0F, 0F, 32, 1, 12);
      Base.setRotationPoint(-16F, 20F, -6F);
      Base.setTextureSize(128, 32);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      Wheel1 = new ModelRenderer(this, 0, 16);
      Wheel1.addBox(0F, 0F, 0F, 2, 2, 1);
      Wheel1.setRotationPoint(-14F, 22F, -6F);
      Wheel1.setTextureSize(128, 32);
      Wheel1.mirror = true;
      setRotation(Wheel1, 0F, 0F, 0F);
      Wheel2 = new ModelRenderer(this, 0, 16);
      Wheel2.addBox(0F, 0F, 0F, 2, 2, 1);
      Wheel2.setRotationPoint(-9F, 22F, -6F);
      Wheel2.setTextureSize(128, 32);
      Wheel2.mirror = true;
      setRotation(Wheel2, 0F, 0F, 0F);
      Wheel3 = new ModelRenderer(this, 0, 16);
      Wheel3.addBox(0F, 0F, 0F, 2, 2, 1);
      Wheel3.setRotationPoint(-14F, 22F, 5F);
      Wheel3.setTextureSize(128, 32);
      Wheel3.mirror = true;
      setRotation(Wheel3, 0F, 0F, 0F);
      Wheel4 = new ModelRenderer(this, 0, 16);
      Wheel4.addBox(0F, 0F, 0F, 2, 2, 1);
      Wheel4.setRotationPoint(-9F, 22F, 5F);
      Wheel4.setTextureSize(128, 32);
      Wheel4.mirror = true;
      setRotation(Wheel4, 0F, 0F, 0F);
      Wheel5 = new ModelRenderer(this, 0, 16);
      Wheel5.addBox(0F, 0F, 0F, 2, 2, 1);
      Wheel5.setRotationPoint(7F, 22F, 5F);
      Wheel5.setTextureSize(128, 32);
      Wheel5.mirror = true;
      setRotation(Wheel5, 0F, 0F, 0F);
      Wheel6 = new ModelRenderer(this, 0, 16);
      Wheel6.addBox(0F, 0F, 0F, 2, 2, 1);
      Wheel6.setRotationPoint(12F, 22F, 5F);
      Wheel6.setTextureSize(128, 32);
      Wheel6.mirror = true;
      setRotation(Wheel6, 0F, 0F, 0F);
      Wheel7 = new ModelRenderer(this, 0, 16);
      Wheel7.addBox(0F, 0F, 0F, 2, 2, 1);
      Wheel7.setRotationPoint(7F, 22F, -6F);
      Wheel7.setTextureSize(128, 32);
      Wheel7.mirror = true;
      setRotation(Wheel7, 0F, 0F, 0F);
      Wheel8 = new ModelRenderer(this, 0, 16);
      Wheel8.addBox(0F, 0F, 0F, 2, 2, 1);
      Wheel8.setRotationPoint(12F, 22F, -6F);
      Wheel8.setTextureSize(128, 32);
      Wheel8.mirror = true;
      setRotation(Wheel8, 0F, 0F, 0F);
      Axel1 = new ModelRenderer(this, 0, 20);
      Axel1.addBox(0F, 0F, 0F, 1, 1, 10);
      Axel1.setRotationPoint(-13.5F, 22.5F, -5F);
      Axel1.setTextureSize(128, 32);
      Axel1.mirror = true;
      setRotation(Axel1, 0F, 0F, 0F);
      Axel2 = new ModelRenderer(this, 0, 20);
      Axel2.addBox(0F, 0F, 0F, 1, 1, 10);
      Axel2.setRotationPoint(-8.5F, 22.5F, -5F);
      Axel2.setTextureSize(128, 32);
      Axel2.mirror = true;
      setRotation(Axel2, 0F, 0F, 0F);
      Axel3 = new ModelRenderer(this, 0, 20);
      Axel3.addBox(0F, 0F, 0F, 1, 1, 10);
      Axel3.setRotationPoint(7.5F, 22.5F, -5F);
      Axel3.setTextureSize(128, 32);
      Axel3.mirror = true;
      setRotation(Axel3, 0F, 0F, 0F);
      Axel4 = new ModelRenderer(this, 0, 20);
      Axel4.addBox(0F, 0F, 0F, 1, 1, 10);
      Axel4.setRotationPoint(12.5F, 22.5F, -5F);
      Axel4.setTextureSize(128, 32);
      Axel4.mirror = true;
      setRotation(Axel4, 0F, 0F, 0F);
      Truck1 = new ModelRenderer(this, 8, 8);
      Truck1.addBox(0F, 0F, 0F, 9, 2, 1);
      Truck1.setRotationPoint(-15F, 21F, -7F);
      Truck1.setTextureSize(128, 32);
      Truck1.mirror = true;
      setRotation(Truck1, 0F, 0F, 0F);
      Truck2 = new ModelRenderer(this, 8, 8);
      Truck2.addBox(0F, 0F, 0F, 9, 2, 1);
      Truck2.setRotationPoint(-15F, 21F, 6F);
      Truck2.setTextureSize(128, 32);
      Truck2.mirror = true;
      setRotation(Truck2, 0F, 0F, 0F);
      Truck3 = new ModelRenderer(this, 8, 8);
      Truck3.addBox(0F, 0F, 0F, 9, 2, 1);
      Truck3.setRotationPoint(6F, 21F, 6F);
      Truck3.setTextureSize(128, 32);
      Truck3.mirror = true;
      setRotation(Truck3, 0F, 0F, 0F);
      Truck4 = new ModelRenderer(this, 8, 8);
      Truck4.addBox(0F, 0F, 0F, 9, 2, 1);
      Truck4.setRotationPoint(6F, 21F, -7F);
      Truck4.setTextureSize(128, 32);
      Truck4.mirror = true;
      setRotation(Truck4, 0F, 0F, 0F);
      HodlingBeam0 = new ModelRenderer(this, 0, 0);
      HodlingBeam0.addBox(0F, 0F, 0F, 1, 12, 1);
      HodlingBeam0.setRotationPoint(-12.8F, 9F, -7F);
      HodlingBeam0.setTextureSize(128, 32);
      HodlingBeam0.mirror = true;
      setRotation(HodlingBeam0, 0F, 0F, 0F);
      HoldingBeam1 = new ModelRenderer(this, 0, 0);
      HoldingBeam1.addBox(0F, 0F, 0F, 1, 12, 1);
      HoldingBeam1.setRotationPoint(-6.4F, 9F, -7F);
      HoldingBeam1.setTextureSize(128, 32);
      HoldingBeam1.mirror = true;
      setRotation(HoldingBeam1, 0F, 0F, 0F);
      HoldingBeam2 = new ModelRenderer(this, 0, 0);
      HoldingBeam2.addBox(0F, 0F, 0F, 1, 12, 1);
      HoldingBeam2.setRotationPoint(0F, 9F, -7F);
      HoldingBeam2.setTextureSize(128, 32);
      HoldingBeam2.mirror = true;
      setRotation(HoldingBeam2, 0F, 0F, 0F);
      HoldingBeam3 = new ModelRenderer(this, 0, 0);
      HoldingBeam3.addBox(0F, 0F, 0F, 1, 12, 1);
      HoldingBeam3.setRotationPoint(6.4F, 9F, -7F);
      HoldingBeam3.setTextureSize(128, 32);
      HoldingBeam3.mirror = true;
      setRotation(HoldingBeam3, 0F, 0F, 0F);
      HoldingBeam4 = new ModelRenderer(this, 0, 0);
      HoldingBeam4.addBox(0F, 0F, 0F, 1, 12, 1);
      HoldingBeam4.setRotationPoint(12.8F, 9F, -7F);
      HoldingBeam4.setTextureSize(128, 32);
      HoldingBeam4.mirror = true;
      setRotation(HoldingBeam4, 0F, 0F, 0F);
      HodlingBeam5 = new ModelRenderer(this, 0, 0);
      HodlingBeam5.addBox(0F, 0F, 0F, 1, 12, 1);
      HodlingBeam5.setRotationPoint(-12.8F, 9F, 6F);
      HodlingBeam5.setTextureSize(128, 32);
      HodlingBeam5.mirror = true;
      setRotation(HodlingBeam5, 0F, 0F, 0F);
      HoldingBeam6 = new ModelRenderer(this, 0, 0);
      HoldingBeam6.addBox(0F, 0F, 0F, 1, 12, 1);
      HoldingBeam6.setRotationPoint(-6.4F, 9F, 6F);
      HoldingBeam6.setTextureSize(128, 32);
      HoldingBeam6.mirror = true;
      setRotation(HoldingBeam6, 0F, 0F, 0F);
      HoldingBeam7 = new ModelRenderer(this, 0, 0);
      HoldingBeam7.addBox(0F, 0F, 0F, 1, 12, 1);
      HoldingBeam7.setRotationPoint(0F, 9F, 6F);
      HoldingBeam7.setTextureSize(128, 32);
      HoldingBeam7.mirror = true;
      setRotation(HoldingBeam7, 0F, 0F, 0F);
      HoldingBeam8 = new ModelRenderer(this, 0, 0);
      HoldingBeam8.addBox(0F, 0F, 0F, 1, 12, 1);
      HoldingBeam8.setRotationPoint(6.4F, 9F, 6F);
      HoldingBeam8.setTextureSize(128, 32);
      HoldingBeam8.mirror = true;
      setRotation(HoldingBeam8, 0F, 0F, 0F);
      HoldingBeam9 = new ModelRenderer(this, 0, 0);
      HoldingBeam9.addBox(0F, 0F, 0F, 1, 12, 1);
      HoldingBeam9.setRotationPoint(12.8F, 9F, 6F);
      HoldingBeam9.setTextureSize(128, 32);
      HoldingBeam9.mirror = true;
      setRotation(HoldingBeam9, 0F, 0F, 0F);
      Coupler1 = new ModelRenderer(this, 16, 16);
      Coupler1.addBox(0F, 0F, 0F, 4, 1, 2);
      Coupler1.setRotationPoint(-18F, 21F, -1F);
      Coupler1.setTextureSize(128, 32);
      Coupler1.mirror = true;
      setRotation(Coupler1, 0F, 0F, 0F);
      Coupler2 = new ModelRenderer(this, 16, 16);
      Coupler2.addBox(0F, 0F, 0F, 4, 1, 2);
      Coupler2.setRotationPoint(14F, 21F, -1F);
      Coupler2.setTextureSize(128, 32);
      Coupler2.mirror = true;
      setRotation(Coupler2, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5){
//	  System.out.println("Rendering empty model");
    Base.render(f5);
    Wheel1.render(f5);
    Wheel2.render(f5);
    Wheel3.render(f5);
    Wheel4.render(f5);
    Wheel5.render(f5);
    Wheel6.render(f5);
    Wheel7.render(f5);
    Wheel8.render(f5);
    Axel1.render(f5);
    Axel2.render(f5);
    Axel3.render(f5);
    Axel4.render(f5);
    Truck1.render(f5);
    Truck2.render(f5);
    Truck3.render(f5);
    Truck4.render(f5);
    HodlingBeam0.render(f5);
    HoldingBeam1.render(f5);
    HoldingBeam2.render(f5);
    HoldingBeam3.render(f5);
    HoldingBeam4.render(f5);
    HodlingBeam5.render(f5);
    HoldingBeam6.render(f5);
    HoldingBeam7.render(f5);
    HoldingBeam8.render(f5);
    HoldingBeam9.render(f5);
    Coupler1.render(f5);
    Coupler2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

  @Override
  public float getRotation(){
	  return 90.0F;
  }

}
